parameters:
#    oh_deer_app.example.class: OhDeer\AppBundle\Example

services:
#    oh_deer_app.example:
#        class: %oh_deer_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
